import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";

import FormHeader from "../../../../Components/InternalSystem/FormHeader";
import Card from "../../../../Components/Details/Card";
import DocumentCard from "../../../../Components/Details/DocumentCard";
import ViewDocument from "../../../../Components/Details/ViewDocument";
import DownloadButton from "../../../../Components/Details/DownloadDocuments";

import "./ReportDetails.css";

export default function ReportDetails() {
    const baseURL = import.meta.env.VITE_API_BASE_URL || "";
    const { reportId } = useParams();

    const [loading, setLoading] = useState(true);
    const [errorMsg, setErrorMsg] = useState("");
    const [details, setDetails] = useState(null);

    useEffect(() => {
        const fetchDetails = async () => {
            if (!reportId) return;

            try {
                setLoading(true);
                setErrorMsg("");

                const res = await fetch(`${baseURL}/api/Reports/${encodeURIComponent(reportId)}`, {
                    credentials: "include",
                });

                if (!res.ok) {
                    const t = await res.text().catch(() => "");
                    throw new Error(t || `Failed to load report details (${res.status}).`);
                }

                const data = await res.json();
                setDetails(data);
            } catch (err) {
                setDetails(null);
                setErrorMsg(err?.message || "Failed to load report details.");
            } finally {
                setLoading(false);
            }
        };

        fetchDetails();
    }, [baseURL, reportId]);

    const docUrls = useMemo(() => {
        if (!reportId) return null;

        return {
            view: `${baseURL}/api/Reports/${encodeURIComponent(reportId)}/document`,
            download: `${baseURL}/api/Reports/${encodeURIComponent(reportId)}/download`,
        };
    }, [baseURL, reportId]);

    const detailsNode = useMemo(() => {
        if (!details) return <div>—</div>;

        const name = details.reportName ?? details.ReportName ?? "—";
        const typeName = details.reportTypeName ?? details.ReportTypeName ?? "—";
        const createdRaw = details.reportCreationTimestamp ?? details.ReportCreationTimestamp ?? null;

        const created = createdRaw ? new Date(createdRaw) : null;
        const createdText = created
            ? `${String(created.getDate()).padStart(2, "0")}/${String(created.getMonth() + 1).padStart(2, "0")}/${created.getFullYear()}`
            : "—";

        const generatedByName = details.generatedByName ?? details.GeneratedByName ?? "—";
        const generatedByEmail = details.generatedByEmail ?? details.GeneratedByEmail ?? "";
        const fileName = details.fileName ?? details.FileName ?? "—";
        const sizeBytes = details.documentSizeBytes ?? details.DocumentSizeBytes ?? null;

        return (
            <div className="text-start">
                <div className="mt-1 ms-2"><strong>Report ID:</strong> {details.reportId ?? details.ReportId ?? "—"}</div>
                <div className="mt-1 ms-2"><strong>Report Name:</strong> {name}</div>
                <div className="mt-1 ms-2"><strong>Report Type:</strong> {typeName}</div>
                <div className="mt-1 ms-2"><strong>Generated On:</strong> {createdText}</div>
                <div className="mt-1 ms-2">
                    <strong>Generated By:</strong> {generatedByName}{generatedByEmail ? ` (${generatedByEmail})` : ""}
                </div>
                <div className="mt-1 ms-2"><strong>File Name:</strong> {fileName}</div>
                <div className="mt-1 ms-2"><strong>Document Size:</strong> {sizeBytes != null ? `${sizeBytes} bytes` : "—"}</div>
            </div>
        );
    }, [details]);

    const hasDocument = useMemo(() => {
        const size = details?.documentSizeBytes ?? details?.DocumentSizeBytes ?? null;
        return Number(size) > 0;
    }, [details]);

    return (
        <div className="container report-page">
            <FormHeader title="Report Details" to="/reports" />

            {loading && <p>Loading...</p>}

            {!loading && errorMsg && (
                <div className="alert alert-danger text-start">{errorMsg}</div>
            )}

            {!loading && !errorMsg && details && (
                <>
                    <div className="report-section">
                        <Card title="Report Details" content={detailsNode} />
                    </div>

                    <div className="report-section">
                        <DocumentCard title="Report Document">
                            <ViewDocument documentUrl={hasDocument ? docUrls?.view : null} />
                            <DownloadButton documentUrl={hasDocument ? docUrls?.download : null} />
                        </DocumentCard>
                    </div>
                </>
            )}
        </div>
    );
}