using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QuickPharmaPlus.Server.ModelsDTO.Report;

namespace QuickPharmaPlus.Server.Services.Reports
{
    public sealed class QuestPdfReportPdfGenerator : IReportPdfGenerator
    {
        private const string Currency = "BHD";

        // Word-like typography
        private const float H1Size = 20f;          // Heading 1
        private const float H2Size = 13f;          // Heading 2
        private const float ParagraphSize = 12.5f; // Body
        private const float ParagraphLineHeight = 1.45f;

        public byte[] Generate(
            ReportGenerateRequestDto request,
            string title,
            TotalRevenueReportDto? totalRevenue = null,
            SupplierRevenueReportDto? supplierRevenue = null,
            CategoryRevenueReportDto? categoryRevenue = null)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var createdUtc = DateTime.UtcNow;
            var createdBh = createdUtc.AddHours(3);

            var doc = Document.Create(container =>
            {
                // =========================
                // TOTAL REVENUE REPORT PATH (existing)
                // =========================
                if (totalRevenue != null)
                {
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        // More breathing room in header
                        page.Header().Column(col =>
                        {
                            col.Spacing(6);

                            col.Item().Text("QuickPharmaPlus").FontSize(18).SemiBold();
                            col.Item().Text(title).FontSize(14).SemiBold();

                            col.Item().PaddingTop(6).Text($"Generated (Bahrain): {createdBh:yyyy-MM-dd HH:mm:ss}")
                                .FontColor(Colors.Grey.Darken1);

                            col.Item().Text($"Generated (UTC): {createdUtc:yyyy-MM-dd HH:mm:ss}")
                                .FontColor(Colors.Grey.Darken1);
                        });

                        page.Content().PaddingTop(20).Column(col =>
                        {
                            col.Spacing(14);

                            H1(col, "Introduction");

                            if (totalRevenue != null)
                            {
                                Paragraph(
                                    col,
                                    "This Total Revenue Report is generated by the QuickPharma+ system to provide a comprehensive financial overview " +
                                    "of sales activity across all registered pharmacy branches within the selected reporting period, reflecting the system’s core objective " +
                                    "of enabling transparent, data-driven financial monitoring and decision-making for pharmacy management. The report aggregates revenue data " +
                                    "derived exclusively from successfully completed and recorded payment transactions, ensuring that all monetary values presented accurately " +
                                    "represent confirmed sales processed through the platform’s integrated order, payment, and inventory workflows. In addition to summarizing " +
                                    "overall revenue performance, the report breaks down sales by key operational dimensions such as suppliers and product categories, allowing " +
                                    "administrators and managers to evaluate purchasing efficiency, supplier contribution, and product demand trends across branches. To support auditing " +
                                    "and reconciliation processes, the report also identifies unsuccessful payments and highlights any orders missing associated payment records, helping " +
                                    "ensure data integrity and financial accountability within the system. Overall, this report serves as a strategic financial analysis tool within QuickPharma+, " +
                                    "supporting operational planning, supplier evaluation, revenue tracking, and compliance-oriented review of pharmacy sales activities.");

                                H2(col, $"Scope: {totalRevenue.ScopeLabel} • Period: {totalRevenue.DateFrom:yyyy-MM-dd} → {totalRevenue.DateTo:yyyy-MM-dd}");
                            }
                            else
                            {
                                Paragraph(
                                    col,
                                    "This report was generated with the request parameters below. " +
                                    "Analytics sections will appear here when report data is provided.");
                            }

                            col.Item().PaddingTop(10);
                            H1(col, "Scope");

                            col.Item().Table(t =>
                            {
                                t.ColumnsDefinition(c =>
                                {
                                    c.ConstantColumn(140);
                                    c.RelativeColumn();
                                });

                                Row(t, "Report Type", request.ReportType);
                                Row(t, "Branch", request.Branch ?? "All branches");
                                Row(t, "Date From", request.DateFrom);
                                Row(t, "Date To", request.DateTo);
                                Row(t, "Category", request.ProductCategory);
                                Row(t, "Supplier", request.Supplier);
                                Row(t, "Product", request.Product);
                            });
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Total Revenue Summary");
                            H2(col, $"{totalRevenue.ScopeLabel} • {totalRevenue.DateFrom:yyyy-MM-dd} → {totalRevenue.DateTo:yyyy-MM-dd}");
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(14);

                            col.Item().Text("Key Metrics").SemiBold().FontSize(14);

                            col.Item().Table(t =>
                            {
                                t.ColumnsDefinition(c =>
                                {
                                    c.RelativeColumn();
                                    c.RelativeColumn();
                                });

                                MetricCell(t, "Successful Payments (Revenue)", FormatMoney(totalRevenue.Kpis.SuccessfulPaymentsTotal));
                                MetricCell(t, "Successful Payments (Count)", totalRevenue.Kpis.SuccessfulPaymentsCount.ToString());

                                MetricCell(t, "Unsuccessful Payments (Amount)", FormatMoney(totalRevenue.Kpis.UnsuccessfulPaymentsTotal));
                                MetricCell(t, "Unsuccessful Payments (Count)", totalRevenue.Kpis.UnsuccessfulPaymentsCount.ToString());

                                MetricCell(t, "Orders Missing Payment Record", totalRevenue.Kpis.OrdersWithMissingPaymentCount.ToString());
                                MetricCell(t, "Line Revenue (Price × Qty)", FormatMoney(totalRevenue.Kpis.LineRevenueTotal));
                            });

                            Paragraph(
                                col,
                                "This section provides a high-level financial overview of the system’s performance during the selected period, focusing on key revenue " +
                                "indicators across all branches. The total revenue reflects the sum of all successfully completed payment transactions, offering a clear measure " +
                                "of realized income within QuickPharma+. The number of successful payments indicates transaction volume and customer purchasing activity, while " +
                                "unsuccessful payments and missing payment records help assess payment reliability and data integrity. Additionally, the comparison between total revenue " +
                                "and line revenue (calculated as product price multiplied by quantity) allows management to evaluate pricing accuracy, discounts, or adjustments applied during checkout.");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    // NEW: KPI per branch pages (unchanged content, just H1/H2 + spacing)
                    foreach (var br in totalRevenue.BranchKpis.OrderBy(x => x.BranchName))
                    {
                        container.Page(page =>
                        {
                            ConfigurePage(page);

                            page.Header().Column(col =>
                            {
                                col.Spacing(6);
                                H1(col, "Branch Revenue Summary");
                                H2(col, $"{br.BranchName} • {totalRevenue.DateFrom:yyyy-MM-dd} → {totalRevenue.DateTo:yyyy-MM-dd}");
                            });

                            page.Content().PaddingTop(18).Column(col =>
                            {
                                col.Spacing(14);

                                col.Item().Text("Key Metrics").SemiBold().FontSize(14);

                                col.Item().Table(t =>
                                {
                                    t.ColumnsDefinition(c =>
                                    {
                                        c.RelativeColumn();
                                        c.RelativeColumn();
                                    });

                                    MetricCell(t, "Successful Payments (Revenue)", FormatMoney(br.Kpis.SuccessfulPaymentsTotal));
                                    MetricCell(t, "Successful Payments (Count)", br.Kpis.SuccessfulPaymentsCount.ToString());

                                    MetricCell(t, "Unsuccessful Payments (Amount)", FormatMoney(br.Kpis.UnsuccessfulPaymentsTotal));
                                    MetricCell(t, "Unsuccessful Payments (Count)", br.Kpis.UnsuccessfulPaymentsCount.ToString());

                                    MetricCell(t, "Orders Missing Payment Record", br.Kpis.OrdersWithMissingPaymentCount.ToString());
                                    MetricCell(t, "Line Revenue (Price × Qty)", FormatMoney(br.Kpis.LineRevenueTotal));
                                });

                                Paragraph(
                                    col,
                                    "This section provides the same KPI structure as the overall summary but scoped to a single branch. " +
                                    "It supports branch-level performance evaluation and comparison.");
                            });

                            page.Footer().AlignCenter().Element(Footer);
                        });
                    }

                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        var supplierTopBottom = TryGetTopAndBottom(
                            totalRevenue.SalesBySupplier,
                            r => r.Revenue,
                            out var topSupplier,
                            out var lowSupplier);

                        page.Header().Column(col =>
                        {
                            col.Item().Text("Sales by Supplier").FontSize(16).SemiBold();
                            col.Item().Text($"{totalRevenue.ScopeLabel} • {totalRevenue.DateFrom:yyyy-MM-dd} → {totalRevenue.DateTo:yyyy-MM-dd}")
                                .FontColor(Colors.Grey.Darken1);
                        });

                        page.Content().PaddingTop(14).Column(col =>
                        {
                            col.Spacing(10);

                            col.Item().Text("Summary (successful paid orders only)").FontColor(Colors.Grey.Darken2);
                            col.Item().Element(c => BuildSalesBySupplierTable(c, totalRevenue.SalesBySupplier));

                            if (supplierTopBottom)
                            {
                                SectionParagraph(
                                    col,
                                    "This section analyzes revenue contribution by supplier, highlighting how different suppliers impact overall sales performance. " +
                                    $"Top supplier: {SafeName(topSupplier!.SupplierName)} ({FormatMoney(topSupplier.Revenue)}). " +
                                    $"Lowest supplier: {SafeName(lowSupplier!.SupplierName)} ({FormatMoney(lowSupplier.Revenue)}).");
                            }
                            else
                            {
                                SectionParagraph(
                                    col,
                                    "This section analyzes revenue contribution by supplier. No supplier sales were recorded for the selected period.");
                            }
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        var categoryTopBottom = TryGetTopAndBottom(
                            totalRevenue.SalesByCategory,
                            r => r.Revenue,
                            out var topCategory,
                            out var lowCategory);

                        page.Header().Column(col =>
                        {
                            col.Item().Text("Sales by Category").FontSize(16).SemiBold();
                            col.Item().Text($"{totalRevenue.ScopeLabel} • {totalRevenue.DateFrom:yyyy-MM-dd} → {totalRevenue.DateTo:yyyy-MM-dd}")
                                .FontColor(Colors.Grey.Darken1);
                        });

                        page.Content().PaddingTop(14).Column(col =>
                        {
                            col.Spacing(10);

                            col.Item().Text("Summary (successful paid orders only)").FontColor(Colors.Grey.Darken2);
                            col.Item().Element(c => BuildSalesByCategoryTable(c, totalRevenue.SalesByCategory));

                            if (categoryTopBottom)
                            {
                                SectionParagraph(
                                    col,
                                    "This section presents sales performance segmented by product category, offering insight into customer demand trends and product mix effectiveness. " +
                                    $"Top category: {SafeName(topCategory!.CategoryName)} ({FormatMoney(topCategory.Revenue)}). " +
                                    $"Lowest category: {SafeName(lowCategory!.CategoryName)} ({FormatMoney(lowCategory.Revenue)}).");
                            }
                            else
                            {
                                SectionParagraph(
                                    col,
                                    "This section presents sales performance segmented by product category. No category sales were recorded for the selected period.");
                            }
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        var productTopBottom = TryGetTopAndBottom(
                            totalRevenue.SalesByProduct,
                            r => r.Profit,
                            out var topProduct,
                            out var lowProduct);

                        page.Header().Column(col =>
                        {
                            col.Item().Text("Sales by Product").FontSize(16).SemiBold();
                            col.Item().Text($"{totalRevenue.ScopeLabel} • {totalRevenue.DateFrom:yyyy-MM-dd} → {totalRevenue.DateTo:yyyy-MM-dd}")
                                .FontColor(Colors.Grey.Darken1);
                        });

                        page.Content().PaddingTop(14).Column(col =>
                        {
                            col.Spacing(10);

                            col.Item().Text("“Profit” is computed as ProductPrice × Quantity (successful paid orders only).")
                                .FontColor(Colors.Grey.Darken2);

                            col.Item().Element(c => BuildSalesByProductTable(c, totalRevenue.SalesByProduct));

                            if (productTopBottom)
                            {
                                SectionParagraph(
                                    col,
                                    "This section provides a detailed view of individual product performance, identifying top-selling and low-performing products based on revenue, " +
                                    "quantity sold, and order frequency. " +
                                    $"Top product: {SafeName(topProduct!.ProductName)} ({FormatMoney(topProduct.Profit)}). " +
                                    $"Lowest product: {SafeName(lowProduct!.ProductName)} ({FormatMoney(lowProduct.Profit)}).");
                            }
                            else
                            {
                                SectionParagraph(
                                    col,
                                    "This section provides a detailed view of individual product performance. No product sales were recorded for the selected period.");
                            }
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Item().Text("Successful Orders").FontSize(16).SemiBold();
                            col.Item().Text($"Filtered by OrderCreationDate • {totalRevenue.DateFrom:yyyy-MM-dd} → {totalRevenue.DateTo:yyyy-MM-dd}")
                                .FontColor(Colors.Grey.Darken1);
                        });

                        page.Content().PaddingTop(14).Column(col =>
                        {
                            col.Spacing(10);
                            col.Item().Text("Orders included: successful paid orders only.").FontColor(Colors.Grey.Darken2);
                            col.Item().Element(c => BuildOrdersTable(c, totalRevenue.Orders));

                            SectionParagraph(
                                col,
                                $"This section lists successfully paid orders created during the reporting period. Total orders listed: {totalRevenue.Orders.Count}.");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Item().Text("Delivery Requests").FontSize(16).SemiBold();
                            col.Item().Text("Derived from Delivery Shippings (successful paid orders only)")
                                .FontColor(Colors.Grey.Darken1);
                        });

                        page.Content().PaddingTop(14).Column(col =>
                        {
                            col.Spacing(10);
                            col.Item().Element(c => BuildDeliveryRequestsTable(c, totalRevenue.DeliveryRequests));

                            SectionParagraph(
                                col,
                                $"This section highlights delivery-based orders derived from shipping records. Total delivery requests in this period: {totalRevenue.DeliveryRequests.Count}.");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Item().Text("Supplier Orders (Company Cost)").FontSize(16).SemiBold();
                            col.Item().Text($"{totalRevenue.ScopeLabel} • {totalRevenue.DateFrom:yyyy-MM-dd} → {totalRevenue.DateTo:yyyy-MM-dd}")
                                .FontColor(Colors.Grey.Darken1);
                        });

                        page.Content().PaddingTop(14).Column(col =>
                        {
                            col.Spacing(10);
                            col.Item().Text("Cost = ProductPrice × Quantity.").FontColor(Colors.Grey.Darken2);
                            col.Item().Element(c => BuildSupplierOrdersTable(c, totalRevenue.SupplierOrders));

                            var supplierOrdersTotal = totalRevenue.SupplierOrders.Sum(x => x.TotalCost);
                            SectionParagraph(
                                col,
                                $"This section estimates supplier purchasing cost for the period. Total supplier-order cost: {FormatMoney(supplierOrdersTotal)}.");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Item().Text("Reorders (No Date Filter)").FontSize(16).SemiBold();
                            col.Item().Text("Cost = ProductPrice × Quantity.").FontColor(Colors.Grey.Darken1);
                        });

                        page.Content().PaddingTop(14).Column(col =>
                        {
                            col.Spacing(10);
                            col.Item().Element(c => BuildReordersTable(c, totalRevenue.Reorders));

                            var reorderTotal = totalRevenue.Reorders.Sum(x => x.TotalCost);
                            SectionParagraph(
                                col,
                                $"This section lists reorder configurations (no date filtering available). Total reorder cost estimate (price × quantity): {FormatMoney(reorderTotal)}.");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });
                }

                // =========================
                // SUPPLIER REVENUE REPORT PATH
                // =========================
                else if (supplierRevenue != null)
                {
                    // 1) intro + supplier details
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Supplier Revenue Report");
                            H2(col, $"{supplierRevenue.SupplierName} • {supplierRevenue.ScopeLabel} • {supplierRevenue.DateFrom:yyyy-MM-dd} → {supplierRevenue.DateTo:yyyy-MM-dd}");

                            col.Item().PaddingTop(6).Text($"Generated (Bahrain): {createdBh:yyyy-MM-dd HH:mm:ss}").FontColor(Colors.Grey.Darken1);
                            col.Item().Text($"Generated (UTC): {createdUtc:yyyy-MM-dd HH:mm:ss}").FontColor(Colors.Grey.Darken1);
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(14);

                            H1(col, "Introduction");
                            Paragraph(col,
                                "This Supplier Revenue Report is generated by the QuickPharmaPlus system to summarize sales performance for a selected supplier " +
                                "during the specified reporting period. All revenue and quantities are derived from successfully paid orders and are computed using " +
                                "supplier-specific product lines only (ProductPrice × Quantity).");

                            H1(col, "Supplier Details");

                            col.Item().Table(t =>
                            {
                                t.ColumnsDefinition(c =>
                                {
                                    c.ConstantColumn(160);
                                    c.RelativeColumn();
                                });

                                Row(t, "Supplier", supplierRevenue.SupplierName);
                                Row(t, "Contact", string.IsNullOrWhiteSpace(supplierRevenue.SupplierContact) ? "—" : supplierRevenue.SupplierContact);
                                Row(t, "Email", string.IsNullOrWhiteSpace(supplierRevenue.SupplierEmail) ? "—" : supplierRevenue.SupplierEmail);
                                Row(t, "Representative", string.IsNullOrWhiteSpace(supplierRevenue.SupplierRepresentative) ? "—" : supplierRevenue.SupplierRepresentative);
                                Row(t, "Scope", supplierRevenue.ScopeLabel);
                                Row(t, "Date From", supplierRevenue.DateFrom.ToString("yyyy-MM-dd"));
                                Row(t, "Date To", supplierRevenue.DateTo.ToString("yyyy-MM-dd"));
                            });
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    // 2) supplier KPI page
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Supplier Revenue Summary");
                            H2(col, $"{supplierRevenue.SupplierName} • {supplierRevenue.ScopeLabel} • {supplierRevenue.DateFrom:yyyy-MM-dd} → {supplierRevenue.DateTo:yyyy-MM-dd}");
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(14);

                            col.Item().Text("Key Metrics").SemiBold().FontSize(14);

                            col.Item().Table(t =>
                            {
                                t.ColumnsDefinition(c =>
                                {
                                    c.RelativeColumn();
                                    c.RelativeColumn();
                                });

                                MetricCell(t, "Successful Payments (Revenue)", FormatMoney(supplierRevenue.Kpis.SuccessfulPaymentsTotal));
                                MetricCell(t, "Successful Payments (Count)", supplierRevenue.Kpis.SuccessfulPaymentsCount.ToString());

                                MetricCell(t, "Unsuccessful Payments (Amount)", FormatMoney(supplierRevenue.Kpis.UnsuccessfulPaymentsTotal));
                                MetricCell(t, "Unsuccessful Payments (Count)", supplierRevenue.Kpis.UnsuccessfulPaymentsCount.ToString());

                                MetricCell(t, "Orders Missing Payment Record", supplierRevenue.Kpis.OrdersWithMissingPaymentCount.ToString());
                                MetricCell(t, "Line Revenue (Price × Qty)", FormatMoney(supplierRevenue.Kpis.LineRevenueTotal));
                            });

                            var k = supplierRevenue.Kpis;

                            Paragraph(
                                col,
                                "This section summarizes the supplier’s overall performance using key financial and data-integrity indicators. " +
                                $"Successful revenue for the selected supplier is {FormatMoney(k.SuccessfulPaymentsTotal)} across {k.SuccessfulPaymentsCount} successful paid orders. " +
                                $"Unsuccessful supplier-line amount is {FormatMoney(k.UnsuccessfulPaymentsTotal)} across {k.UnsuccessfulPaymentsCount} unsuccessful payment attempts. " +
                                $"Orders missing a payment record: {k.OrdersWithMissingPaymentCount}. " +
                                "All revenue values are supplier-specific and derived from product line calculations (ProductPrice × Quantity), not from full cart totals.");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });



                    // 3) KPI per branch pages (H1/H2)
                    var hasBranchTopBottom = TryGetTopAndBottom(
                        supplierRevenue.BranchKpis,
                        x => x.Kpis.SuccessfulPaymentsTotal,
                        out var topBranch,
                        out var lowBranch);

                    foreach (var br in supplierRevenue.BranchKpis.OrderBy(x => x.BranchName))
                    {
                        container.Page(page =>
                        {
                            ConfigurePage(page);

                            page.Header().Column(col =>
                            {
                                col.Spacing(6);
                                H1(col, "Supplier Revenue Summary (Branch)");
                                H2(col, $"{supplierRevenue.SupplierName} • {br.BranchName} • {supplierRevenue.DateFrom:yyyy-MM-dd} → {supplierRevenue.DateTo:yyyy-MM-dd}");
                            });

                            page.Content().PaddingTop(18).Column(col =>
                            {
                                col.Spacing(14);

                                col.Item().Text("Key Metrics").SemiBold().FontSize(14);

                                col.Item().Table(t =>
                                {
                                    t.ColumnsDefinition(c =>
                                    {
                                        c.RelativeColumn();
                                        c.RelativeColumn();
                                    });

                                    MetricCell(t, "Successful Payments (Revenue)", FormatMoney(br.Kpis.SuccessfulPaymentsTotal));
                                    MetricCell(t, "Successful Payments (Count)", br.Kpis.SuccessfulPaymentsCount.ToString());

                                    MetricCell(t, "Unsuccessful Payments (Amount)", FormatMoney(br.Kpis.UnsuccessfulPaymentsTotal));
                                    MetricCell(t, "Unsuccessful Payments (Count)", br.Kpis.UnsuccessfulPaymentsCount.ToString());

                                    MetricCell(t, "Orders Missing Payment Record", br.Kpis.OrdersWithMissingPaymentCount.ToString());
                                    MetricCell(t, "Line Revenue (Price × Qty)", FormatMoney(br.Kpis.LineRevenueTotal));
                                });

                                if (hasBranchTopBottom)
                                {
                                    Paragraph(
                                        col,
                                        "This page provides branch-scoped KPIs for the selected supplier, enabling branch-by-branch comparison. " +
                                        $"Highest supplier revenue branch: {topBranch!.BranchName} ({FormatMoney(topBranch.Kpis.SuccessfulPaymentsTotal)}). " +
                                        $"Lowest supplier revenue branch: {lowBranch!.BranchName} ({FormatMoney(lowBranch.Kpis.SuccessfulPaymentsTotal)}). " +
                                        "Differences across branches can reflect local demand patterns, stocking strategy, or branch-specific purchasing behavior.");
                                }
                                else
                                {
                                    Paragraph(
                                        col,
                                        "This page provides branch-scoped KPIs for the selected supplier. No supplier revenue was recorded in the selected scope and period.");
                                }
                            });

                            page.Footer().AlignCenter().Element(Footer);
                        });
                    }

                    // 4) supplier product list (sales by product)
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Supplier Product Sales");
                            H2(col, $"{supplierRevenue.SupplierName} • {supplierRevenue.ScopeLabel} • {supplierRevenue.DateFrom:yyyy-MM-dd} → {supplierRevenue.DateTo:yyyy-MM-dd}");
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(12);
                            col.Item().Text("Successful paid orders only.").FontColor(Colors.Grey.Darken2);
                            col.Item().Element(c => BuildSupplierProductSalesTable(c, supplierRevenue.ProductSales));

                            var hasProductTopBottom = TryGetTopAndBottom(
                                supplierRevenue.ProductSales,
                                x => x.Revenue,
                                out var topProduct,
                                out var lowProduct);

                            if (hasProductTopBottom)
                            {
                                Paragraph(
                                    col,
                                    "This section analyzes the supplier’s performance at the product level, highlighting products that drive the majority of supplier revenue. " +
                                    $"Top product: {SafeName(topProduct!.ProductName)} ({FormatMoney(topProduct.Revenue)}). " +
                                    $"Lowest product: {SafeName(lowProduct!.ProductName)} ({FormatMoney(lowProduct.Revenue)}).");
                            }
                            else
                            {
                                Paragraph(
                                    col,
                                    "This section analyzes the supplier’s performance at the product level. No product sales were recorded for the selected supplier in this period.");
                            }
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    // 5) supplier order list (sales orders)
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Supplier Sales Orders");
                            H2(col, $"{supplierRevenue.SupplierName} • Filtered by OrderCreationDate • {supplierRevenue.DateFrom:yyyy-MM-dd} → {supplierRevenue.DateTo:yyyy-MM-dd}");
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(12);
                            col.Item().Text("Each order shows supplier-only revenue.").FontColor(Colors.Grey.Darken2);
                            col.Item().Element(c => BuildSupplierSalesOrdersTable(c, supplierRevenue.Orders));


                            Paragraph(
                                col,
                                "This section lists customer orders that included at least one product from the selected supplier (successful paid orders only). " +
                                "Each row includes the supplier-only revenue amount for that order, enabling traceability from totals back to individual transactions. " +
                                "This supports auditing and validation of supplier revenue calculations at order level.");

                            var salesOrderTotal = supplierRevenue.Orders.Sum(x => x.SupplierLineRevenue);

                            Paragraph(
                                col,
                                $"Total supplier revenue across listed orders: {FormatMoney(salesOrderTotal)}.");

                        });
                        page.Footer().AlignCenter().Element(Footer);
                    });

                    // 6) supplier supplier orders list (company purchases)
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Supplier Orders (Company Purchases)");
                            H2(col, $"{supplierRevenue.SupplierName} • {supplierRevenue.ScopeLabel} • {supplierRevenue.DateFrom:yyyy-MM-dd} → {supplierRevenue.DateTo:yyyy-MM-dd}");
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(12);
                            col.Item().Text("Filtered by SupplierOrderDate.").FontColor(Colors.Grey.Darken2);
                            col.Item().Element(c => BuildSupplierOrdersTable(c, supplierRevenue.SupplierOrders));

                            var procurementTotal = supplierRevenue.SupplierOrders.Sum(x => x.TotalCost);

                            Paragraph(
                                col,
                                "This section shifts from sales to procurement, listing supplier orders placed by the company for this supplier during the selected period. " +
                                $"Total procurement cost for this supplier in the period: {FormatMoney(procurementTotal)}. " +
                                "Comparing procurement cost to supplier sales revenue helps assess supplier cost-effectiveness and inventory investment.");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    // 7) supplier reorders list
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Reorders for Supplier");
                            H2(col, $"{supplierRevenue.SupplierName} • No Date Filter");
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(12);
                            col.Item().Element(c => BuildReordersTable(c, supplierRevenue.Reorders));

                            var reorderTotal = supplierRevenue.Reorders.Sum(x => x.TotalCost);

                            Paragraph(
                                col,
                                "This section lists reorder configurations linked to the selected supplier (no date filtering available). " +
                                "Reorders represent proactive inventory planning rules that help maintain availability for high-demand supplier products. " +
                                $"Total reorder cost estimate (price × quantity): {FormatMoney(reorderTotal)}.");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    // 8) appendix
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Appendix");
                            H2(col, "Request Parameters");
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(12);

                            col.Item().Table(t =>
                            {
                                t.ColumnsDefinition(c =>
                                {
                                    c.ConstantColumn(140);
                                    c.RelativeColumn();
                                });

                                Row(t, "Report Type", request.ReportType);
                                Row(t, "Branch", request.Branch ?? "All branches");
                                Row(t, "Date From", request.DateFrom);
                                Row(t, "Date To", request.DateTo);
                                Row(t, "Supplier", request.Supplier);
                            });
                            
                            
                            Paragraph(
                                col,
                                "Appendix: This page documents the request parameters used to generate the report. " +
                                "Data integrity note: all figures are supplier-specific and computed from the selected supplier’s product lines only (ProductPrice × Quantity). " +
                                "KPI payment status is based on payment records; list sections are filtered to successful paid orders to ensure financial accuracy and audit readiness.");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });
                }
                else if (categoryRevenue != null)
                {
                    // 1) intro + category details
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Category Revenue Report");
                            H2(col, $"{categoryRevenue.CategoryName} • {categoryRevenue.ScopeLabel} • {categoryRevenue.DateFrom:yyyy-MM-dd} → {categoryRevenue.DateTo:yyyy-MM-dd}");

                            col.Item().PaddingTop(6).Text($"Generated (Bahrain): {createdBh:yyyy-MM-dd HH:mm:ss}").FontColor(Colors.Grey.Darken1);
                            col.Item().Text($"Generated (UTC): {createdUtc:yyyy-MM-dd HH:mm:ss}").FontColor(Colors.Grey.Darken1);
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(14);

                            H1(col, "Introduction");
                            Paragraph(
                                col,
                                "This Category Revenue Report is generated by the QuickPharmaPlus system to summarize sales performance for a selected product category " +
                                "during the specified reporting period. Revenue and quantities are derived from successfully paid orders and are computed using category-specific " +
                                "product lines only (ProductPrice × Quantity). The report further breaks the category into its product types and lists the products under each type " +
                                "to support deeper analysis of demand distribution within the category.");

                            H1(col, "Category Details");

                            col.Item().Table(t =>
                            {
                                t.ColumnsDefinition(c =>
                                {
                                    c.ConstantColumn(160);
                                    c.RelativeColumn();
                                });

                                Row(t, "Category", categoryRevenue.CategoryName);
                                Row(t, "Scope", categoryRevenue.ScopeLabel);
                                Row(t, "Date From", categoryRevenue.DateFrom.ToString("yyyy-MM-dd"));
                                Row(t, "Date To", categoryRevenue.DateTo.ToString("yyyy-MM-dd"));
                            });
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    // 2) category KPI page
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Category Revenue Summary");
                            H2(col, $"{categoryRevenue.CategoryName} • {categoryRevenue.ScopeLabel} • {categoryRevenue.DateFrom:yyyy-MM-dd} → {categoryRevenue.DateTo:yyyy-MM-dd}");
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(14);

                            col.Item().Text("Key Metrics").SemiBold().FontSize(14);

                            col.Item().Table(t =>
                            {
                                t.ColumnsDefinition(c =>
                                {
                                    c.RelativeColumn();
                                    c.RelativeColumn();
                                });

                                MetricCell(t, "Successful Payments (Revenue)", FormatMoney(categoryRevenue.Kpis.SuccessfulPaymentsTotal));
                                MetricCell(t, "Successful Payments (Count)", categoryRevenue.Kpis.SuccessfulPaymentsCount.ToString());

                                MetricCell(t, "Unsuccessful Payments (Amount)", FormatMoney(categoryRevenue.Kpis.UnsuccessfulPaymentsTotal));
                                MetricCell(t, "Unsuccessful Payments (Count)", categoryRevenue.Kpis.UnsuccessfulPaymentsCount.ToString());

                                MetricCell(t, "Orders Missing Payment Record", categoryRevenue.Kpis.OrdersWithMissingPaymentCount.ToString());
                                MetricCell(t, "Line Revenue (Price × Qty)", FormatMoney(categoryRevenue.Kpis.LineRevenueTotal));
                            });

                            var k = categoryRevenue.Kpis;

                            Paragraph(
                                col,
                                "This section summarizes the selected category’s overall performance using key financial and data-integrity indicators. " +
                                $"Successful category revenue is {FormatMoney(k.SuccessfulPaymentsTotal)} across {k.SuccessfulPaymentsCount} successful paid orders. " +
                                $"Unsuccessful category-line amount is {FormatMoney(k.UnsuccessfulPaymentsTotal)} across {k.UnsuccessfulPaymentsCount} unsuccessful payment attempts. " +
                                $"Orders missing a payment record: {k.OrdersWithMissingPaymentCount}. " +
                                "All revenue values are category-specific and derived from product line calculations (ProductPrice × Quantity).");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    // 3) KPI per branch pages (same pattern as supplier)
                    var hasBranchTopBottom = TryGetTopAndBottom(
                        categoryRevenue.BranchKpis,
                        x => x.Kpis.SuccessfulPaymentsTotal,
                        out var topBranch,
                        out var lowBranch);

                    foreach (var br in categoryRevenue.BranchKpis.OrderBy(x => x.BranchName))
                    {
                        container.Page(page =>
                        {
                            ConfigurePage(page);

                            page.Header().Column(col =>
                            {
                                col.Spacing(6);
                                H1(col, "Category Revenue Summary (Branch)");
                                H2(col, $"{categoryRevenue.CategoryName} • {br.BranchName} • {categoryRevenue.DateFrom:yyyy-MM-dd} → {categoryRevenue.DateTo:yyyy-MM-dd}");
                            });

                            page.Content().PaddingTop(18).Column(col =>
                            {
                                col.Spacing(14);

                                col.Item().Text("Key Metrics").SemiBold().FontSize(14);

                                col.Item().Table(t =>
                                {
                                    t.ColumnsDefinition(c =>
                                    {
                                        c.RelativeColumn();
                                        c.RelativeColumn();
                                    });

                                    MetricCell(t, "Successful Payments (Revenue)", FormatMoney(br.Kpis.SuccessfulPaymentsTotal));
                                    MetricCell(t, "Successful Payments (Count)", br.Kpis.SuccessfulPaymentsCount.ToString());

                                    MetricCell(t, "Unsuccessful Payments (Amount)", FormatMoney(br.Kpis.UnsuccessfulPaymentsTotal));
                                    MetricCell(t, "Unsuccessful Payments (Count)", br.Kpis.UnsuccessfulPaymentsCount.ToString());

                                    MetricCell(t, "Orders Missing Payment Record", br.Kpis.OrdersWithMissingPaymentCount.ToString());
                                    MetricCell(t, "Line Revenue (Price × Qty)", FormatMoney(br.Kpis.LineRevenueTotal));
                                });

                                if (hasBranchTopBottom)
                                {
                                    Paragraph(
                                        col,
                                        "This page provides branch-scoped KPIs for the selected category, enabling branch-by-branch comparison. " +
                                        $"Highest category revenue branch: {topBranch!.BranchName} ({FormatMoney(topBranch.Kpis.SuccessfulPaymentsTotal)}). " +
                                        $"Lowest category revenue branch: {lowBranch!.BranchName} ({FormatMoney(lowBranch.Kpis.SuccessfulPaymentsTotal)}).");
                                }
                                else
                                {
                                    Paragraph(
                                        col,
                                        "This page provides branch-scoped KPIs for the selected category. No category revenue was recorded in the selected scope and period.");
                                }
                            });

                            page.Footer().AlignCenter().Element(Footer);
                        });
                    }

                    // 4) Type -> product breakdown pages
                    foreach (var type in categoryRevenue.TypeSales.OrderByDescending(x => x.Revenue).ThenBy(x => x.ProductTypeName))
                    {
                        container.Page(page =>
                        {
                            ConfigurePage(page);

                            page.Header().Column(col =>
                            {
                                col.Spacing(6);
                                H1(col, "Category Type Performance");
                                H2(col, $"{categoryRevenue.CategoryName} • {type.ProductTypeName} • {categoryRevenue.DateFrom:yyyy-MM-dd} → {categoryRevenue.DateTo:yyyy-MM-dd}");
                            });

                            page.Content().PaddingTop(18).Column(col =>
                            {
                                col.Spacing(12);

                                Paragraph(
                                    col,
                                    $"Type revenue: {FormatMoney(type.Revenue)} • Orders: {type.OrdersCount} • Units sold: {type.UnitsSold}. " +
                                    "The table below lists products under this type and their category-specific revenue contribution (successful paid orders only).");

                                col.Item().Element(c => BuildCategoryTypeProductsTable(c, type.Products));
                            });

                            page.Footer().AlignCenter().Element(Footer);
                        });
                    }

                    // 5) category orders list
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Category Sales Orders");
                            H2(col, $"{categoryRevenue.CategoryName} • Filtered by OrderCreationDate • {categoryRevenue.DateFrom:yyyy-MM-dd} → {categoryRevenue.DateTo:yyyy-MM-dd}");
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(12);

                            col.Item().Text("Each order shows category-only revenue.").FontColor(Colors.Grey.Darken2);
                            col.Item().Element(c => BuildCategorySalesOrdersTable(c, categoryRevenue.Orders));

                            var ordersTotal = categoryRevenue.Orders.Sum(x => x.CategoryLineRevenue);

                            Paragraph(
                                col,
                                "This section lists customer orders that included at least one product from the selected category (successful paid orders only). " +
                                $"Total category revenue across listed orders: {FormatMoney(ordersTotal)}.");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });

                    // 6) appendix
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            H1(col, "Appendix");
                            H2(col, "Request Parameters");
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(12);

                            col.Item().Table(t =>
                            {
                                t.ColumnsDefinition(c =>
                                {
                                    c.ConstantColumn(140);
                                    c.RelativeColumn();
                                });

                                Row(t, "Report Type", request.ReportType);
                                Row(t, "Branch", request.Branch ?? "All branches");
                                Row(t, "Date From", request.DateFrom);
                                Row(t, "Date To", request.DateTo);
                                Row(t, "Category", request.ProductCategory);
                            });

                            Paragraph(
                                col,
                                "Data integrity note: all figures are category-specific and computed from the selected category’s product lines only (ProductPrice × Quantity). " +
                                "The report breaks down performance by category type and product to help identify demand concentration within the selected category.");
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });
                }
                else
                {
                    // optional: a single fallback page if neither DTO was provided
                    container.Page(page =>
                    {
                        ConfigurePage(page);

                        page.Header().Column(col =>
                        {
                            col.Spacing(6);
                            col.Item().Text("QuickPharmaPlus").FontSize(18).SemiBold();
                            col.Item().Text(title).FontSize(14).SemiBold();
                        });

                        page.Content().PaddingTop(18).Column(col =>
                        {
                            col.Spacing(10);
                            H1(col, "Scope");

                            col.Item().Table(t =>
                            {
                                t.ColumnsDefinition(c =>
                                {
                                    c.ConstantColumn(140);
                                    c.RelativeColumn();
                                });

                                Row(t, "Report Type", request.ReportType);
                                Row(t, "Branch", request.Branch ?? "All branches");
                                Row(t, "Date From", request.DateFrom);
                                Row(t, "Date To", request.DateTo);
                                Row(t, "Supplier", request.Supplier);
                            });
                        });

                        page.Footer().AlignCenter().Element(Footer);
                    });
                }
            });

            return doc.GeneratePdf();
        }

        private static void ConfigurePage(PageDescriptor page)
        {
            page.Size(PageSizes.A4);
            page.Margin(32);
            page.DefaultTextStyle(x => x.FontSize(11));
        }

        private static void H1(ColumnDescriptor col, string text) =>
            col.Item().PaddingBottom(2).Text(text).FontSize(H1Size).SemiBold();

        private static void H2(ColumnDescriptor col, string text) =>
            col.Item().PaddingBottom(6).Text(text).FontSize(H2Size).FontColor(Colors.Grey.Darken1);

        private static void Paragraph(ColumnDescriptor col, string text) =>
            col.Item()
                .PaddingTop(8)
                .Text(text)
                .FontSize(ParagraphSize)
                .LineHeight(ParagraphLineHeight)
                .FontColor(Colors.Grey.Darken2);

        private static void Footer(IContainer c)
        {
            c.Text(x =>
            {
                x.Span("Page ");
                x.CurrentPageNumber();
                x.Span(" / ");
                x.TotalPages();
            });
        }

        private static void Row(TableDescriptor t, string k, string? v)
        {
            t.Cell().Element(CellKey).Text(k);
            t.Cell().Element(CellVal).Text(string.IsNullOrWhiteSpace(v) ? "—" : v);
        }

        private static IContainer CellKey(IContainer c) =>
            c.PaddingVertical(4).PaddingRight(8).DefaultTextStyle(x => x.SemiBold());

        private static IContainer CellVal(IContainer c) =>
            c.PaddingVertical(4);

        private static string FormatMoney(decimal value) =>
            $"{value:0.000} {Currency}";

        private static void MetricCell(TableDescriptor t, string label, string value)
        {
            t.Cell().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(10).Column(col =>
            {
                col.Item().Text(label).FontColor(Colors.Grey.Darken1).FontSize(10);
                col.Item().Text(value).FontSize(14).SemiBold();
            });
        }

        private static void SectionParagraph(ColumnDescriptor col, string text)
        {
            col.Item()
                .PaddingTop(6)
                .Text(text)
                .FontColor(Colors.Grey.Darken2);
        }

        private static string SafeName(string? name) =>
            string.IsNullOrWhiteSpace(name) ? "—" : name;

        private static bool TryGetTopAndBottom<T>(
            List<T> rows,
            Func<T, decimal> valueSelector,
            out T? top,
            out T? bottom)
        {
            top = default;
            bottom = default;

            if (rows == null || rows.Count == 0) return false;

            top = rows
                .OrderByDescending(valueSelector)
                .First();

            bottom = rows
                .OrderBy(valueSelector)
                .First();

            return true;
        }

        private static IContainer BuildSalesBySupplierTable(IContainer container, List<SalesBySupplierRowDto> rows)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(4);
                    c.RelativeColumn(2);
                    c.RelativeColumn(2);
                    c.RelativeColumn(3);
                });

                HeaderCell(t, "Supplier");
                HeaderCell(t, "# Orders");
                HeaderCell(t, "Units Sold");
                HeaderCell(t, $"Revenue ({Currency})");

                if (rows.Count == 0)
                {
                    BodyCell(t, "—");
                    BodyCell(t, "0");
                    BodyCell(t, "0");
                    BodyCell(t, FormatMoney(0m));
                    return;
                }

                foreach (var r in rows)
                {
                    BodyCell(t, r.SupplierName);
                    BodyCell(t, r.OrdersCount.ToString());
                    BodyCell(t, r.UnitsSold.ToString());
                    BodyCell(t, $"{r.Revenue:0.000}");
                }
            });

            return container;
        }

        private static IContainer BuildSalesByCategoryTable(IContainer container, List<SalesByCategoryRowDto> rows)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(4);
                    c.RelativeColumn(2);
                    c.RelativeColumn(2);
                    c.RelativeColumn(3);
                });

                HeaderCell(t, "Category");
                HeaderCell(t, "# Orders");
                HeaderCell(t, "Units Sold");
                HeaderCell(t, $"Revenue ({Currency})");

                if (rows.Count == 0)
                {
                    BodyCell(t, "—");
                    BodyCell(t, "0");
                    BodyCell(t, "0");
                    BodyCell(t, FormatMoney(0m));
                    return;
                }

                foreach (var r in rows)
                {
                    BodyCell(t, r.CategoryName);
                    BodyCell(t, r.OrdersCount.ToString());
                    BodyCell(t, r.UnitsSold.ToString());
                    BodyCell(t, $"{r.Revenue:0.000}");
                }
            });

            return container;
        }

        private static IContainer BuildSalesByProductTable(IContainer container, List<SalesByProductRowDto> rows)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(5);
                    c.RelativeColumn(2);
                    c.RelativeColumn(2);
                    c.RelativeColumn(3);
                });

                HeaderCell(t, "Product");
                HeaderCell(t, "# Orders");
                HeaderCell(t, "Units Sold");
                HeaderCell(t, $"Profit ({Currency})");

                if (rows.Count == 0)
                {
                    BodyCell(t, "—");
                    BodyCell(t, "0");
                    BodyCell(t, "0");
                    BodyCell(t, FormatMoney(0m));
                    return;
                }

                foreach (var r in rows)
                {
                    BodyCell(t, r.ProductName);
                    BodyCell(t, r.OrdersCount.ToString());
                    BodyCell(t, r.UnitsSold.ToString());
                    BodyCell(t, $"{r.Profit:0.000}");
                }
            });

            return container;
        }

        private static IContainer BuildOrdersTable(IContainer container, List<OrderListRowDto> rows)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(2); // id
                    c.RelativeColumn(3); // date
                    c.RelativeColumn(4); // customer
                    c.RelativeColumn(3); // type
                    c.RelativeColumn(3); // total
                });

                HeaderCell(t, "Order #");
                HeaderCell(t, "Created");
                HeaderCell(t, "Customer");
                HeaderCell(t, "Shipping");
                HeaderCell(t, $"Total ({Currency})");

                if (rows.Count == 0)
                {
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, FormatMoney(0m));
                    return;
                }

                foreach (var r in rows)
                {
                    BodyCell(t, r.OrderId.ToString());
                    BodyCell(t, r.OrderCreationDate.HasValue ? r.OrderCreationDate.Value.ToString("yyyy-MM-dd HH:mm") : "—");
                    BodyCell(t, string.IsNullOrWhiteSpace(r.CustomerName) ? "—" : r.CustomerName);

                    var ship =
                        r.IsDelivery == true
                            ? (r.IsUrgent == true ? "Delivery (Urgent)" : "Delivery")
                            : "Pickup";

                    BodyCell(t, ship);
                    BodyCell(t, $"{(r.OrderTotal ?? 0m):0.000}");
                }
            });

            return container;
        }

        private static IContainer BuildDeliveryRequestsTable(IContainer container, List<DeliveryRequestRowDto> rows)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(2); // order
                    c.RelativeColumn(2); // shipping
                    c.RelativeColumn(4); // customer
                    c.RelativeColumn(5); // location
                    c.RelativeColumn(3); // slot/urgent
                });

                HeaderCell(t, "Order #");
                HeaderCell(t, "Shipping #");
                HeaderCell(t, "Recipient");
                HeaderCell(t, "Location");
                HeaderCell(t, "Slot / Urgent");

                if (rows.Count == 0)
                {
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    return;
                }

                foreach (var r in rows)
                {
                    BodyCell(t, r.OrderId.ToString());
                    BodyCell(t, r.ShippingId.ToString());
                    BodyCell(t, string.IsNullOrWhiteSpace(r.CustomerName) ? "—" : r.CustomerName);
                    BodyCell(t, string.IsNullOrWhiteSpace(r.Location) ? "—" : r.Location);

                    var slot = r.IsUrgent ? "Urgent" : (string.IsNullOrWhiteSpace(r.SlotName) ? "—" : r.SlotName);
                    BodyCell(t, slot);
                }
            });

            return container;
        }

        private static IContainer BuildSupplierOrdersTable(IContainer container, List<SupplierOrderCostRowDto> rows)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(2); // id
                    c.RelativeColumn(3); // date
                    c.RelativeColumn(4); // supplier
                    c.RelativeColumn(5); // product
                    c.RelativeColumn(2); // qty
                    c.RelativeColumn(3); // cost
                });

                HeaderCell(t, "SO #");
                HeaderCell(t, "Date");
                HeaderCell(t, "Supplier");
                HeaderCell(t, "Product");
                HeaderCell(t, "Qty");
                HeaderCell(t, $"Cost ({Currency})");

                if (rows.Count == 0)
                {
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "0");
                    BodyCell(t, FormatMoney(0m));
                    return;
                }

                foreach (var r in rows)
                {
                    BodyCell(t, r.SupplierOrderId.ToString());
                    BodyCell(t, r.SupplierOrderDate.HasValue ? r.SupplierOrderDate.Value.ToString("yyyy-MM-dd") : "—");
                    BodyCell(t, string.IsNullOrWhiteSpace(r.SupplierName) ? "—" : r.SupplierName);
                    BodyCell(t, string.IsNullOrWhiteSpace(r.ProductName) ? "—" : r.ProductName);
                    BodyCell(t, r.Quantity.ToString());
                    BodyCell(t, $"{r.TotalCost:0.000}");
                }
            });

            return container;
        }

        private static IContainer BuildReordersTable(IContainer container, List<ReorderCostRowDto> rows)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(2); // id
                    c.RelativeColumn(5); // product
                    c.RelativeColumn(4); // supplier
                    c.RelativeColumn(2); // threshold
                    c.RelativeColumn(2); // qty
                    c.RelativeColumn(3); // cost
                });

                HeaderCell(t, "Reorder #");
                HeaderCell(t, "Product");
                HeaderCell(t, "Supplier");
                HeaderCell(t, "Threshold");
                HeaderCell(t, "Qty");
                HeaderCell(t, $"Cost ({Currency})");

                if (rows.Count == 0)
                {
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "0");
                    BodyCell(t, FormatMoney(0m));
                    return;
                }

                foreach (var r in rows)
                {
                    BodyCell(t, r.ReorderId.ToString());
                    BodyCell(t, string.IsNullOrWhiteSpace(r.ProductName) ? "—" : r.ProductName);
                    BodyCell(t, string.IsNullOrWhiteSpace(r.SupplierName) ? "—" : r.SupplierName);
                    BodyCell(t, r.Threshold?.ToString() ?? "—");
                    BodyCell(t, r.Quantity.ToString());
                    BodyCell(t, $"{r.TotalCost:0.000}");
                }
            });

            return container;
        }

        private static void HeaderCell(TableDescriptor t, string text) =>
            t.Cell().Background(Colors.Grey.Lighten3).Padding(6).Text(text).SemiBold();

        private static void BodyCell(TableDescriptor t, string text) =>
            t.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten3).Padding(6).Text(text);

        private static IContainer BuildSupplierProductSalesTable(IContainer container, List<SupplierProductSalesRowDto> rows)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(6);
                    c.RelativeColumn(2);
                    c.RelativeColumn(2);
                    c.RelativeColumn(3);
                });

                HeaderCell(t, "Product");
                HeaderCell(t, "# Orders");
                HeaderCell(t, "Units Sold");
                HeaderCell(t, $"Revenue ({Currency})");

                if (rows.Count == 0)
                {
                    BodyCell(t, "—");
                    BodyCell(t, "0");
                    BodyCell(t, "0");
                    BodyCell(t, FormatMoney(0m));
                    return;
                }



                foreach (var r in rows)
                {
                    BodyCell(t, r.ProductName);
                    BodyCell(t, r.OrdersCount.ToString());
                    BodyCell(t, r.UnitsSold.ToString());
                    BodyCell(t, $"{r.Revenue:0.000}");
                }
            });

            return container;
        }

        private static IContainer BuildSupplierSalesOrdersTable(IContainer container, List<SupplierSalesOrderRowDto> rows)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(2); // id
                    c.RelativeColumn(3); // date
                    c.RelativeColumn(4); // customer
                    c.RelativeColumn(3); // branch
                    c.RelativeColumn(3); // shipping
                    c.RelativeColumn(3); // supplier revenue
                });

                HeaderCell(t, "Order #");
                HeaderCell(t, "Created");
                HeaderCell(t, "Customer");
                HeaderCell(t, "Branch");
                HeaderCell(t, "Shipping");
                HeaderCell(t, $"Supplier Revenue ({Currency})");

                if (rows.Count == 0)
                {
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, FormatMoney(0m));
                    return;
                }

                foreach (var r in rows)
                {
                    BodyCell(t, r.OrderId.ToString());
                    BodyCell(t, r.OrderCreationDate.HasValue ? r.OrderCreationDate.Value.ToString("yyyy-MM-dd HH:mm") : "—");
                    BodyCell(t, string.IsNullOrWhiteSpace(r.CustomerName) ? "—" : r.CustomerName);
                    BodyCell(t, string.IsNullOrWhiteSpace(r.BranchName) ? "—" : r.BranchName);

                    var ship =
                        r.IsDelivery == true
                            ? (r.IsUrgent == true ? "Delivery (Urgent)" : "Delivery")
                            : "Pickup";

                    BodyCell(t, ship);
                    BodyCell(t, $"{r.SupplierLineRevenue:0.000}");
                }
            });

            return container;
        }

        private static IContainer BuildCategoryTypeProductsTable(IContainer container, List<CategoryTypeProductRevenueRowDto> rows)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(6);
                    c.RelativeColumn(2);
                    c.RelativeColumn(2);
                    c.RelativeColumn(3);
                });

                HeaderCell(t, "Product");
                HeaderCell(t, "# Orders");
                HeaderCell(t, "Units Sold");
                HeaderCell(t, $"Revenue ({Currency})");

                if (rows.Count == 0)
                {
                    BodyCell(t, "—");
                    BodyCell(t, "0");
                    BodyCell(t, "0");
                    BodyCell(t, FormatMoney(0m));
                    return;
                }

                foreach (var r in rows)
                {
                    BodyCell(t, r.ProductName);
                    BodyCell(t, r.OrdersCount.ToString());
                    BodyCell(t, r.UnitsSold.ToString());
                    BodyCell(t, $"{r.Revenue:0.000}");
                }
            });

            return container;
        }

        private static IContainer BuildCategorySalesOrdersTable(IContainer container, List<CategorySalesOrderRowDto> rows)
        {
            container.Table(t =>
            {
                t.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(2); // id
                    c.RelativeColumn(3); // date
                    c.RelativeColumn(4); // customer
                    c.RelativeColumn(3); // branch
                    c.RelativeColumn(3); // shipping
                    c.RelativeColumn(3); // category revenue
                });

                HeaderCell(t, "Order #");
                HeaderCell(t, "Created");
                HeaderCell(t, "Customer");
                HeaderCell(t, "Branch");
                HeaderCell(t, "Shipping");
                HeaderCell(t, $"Category Revenue ({Currency})");

                if (rows.Count == 0)
                {
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, "—");
                    BodyCell(t, FormatMoney(0m));
                    return;
                }

                foreach (var r in rows)
                {
                    BodyCell(t, r.OrderId.ToString());
                    BodyCell(t, r.OrderCreationDate.HasValue ? r.OrderCreationDate.Value.ToString("yyyy-MM-dd HH:mm") : "—");
                    BodyCell(t, string.IsNullOrWhiteSpace(r.CustomerName) ? "—" : r.CustomerName);
                    BodyCell(t, string.IsNullOrWhiteSpace(r.BranchName) ? "—" : r.BranchName);

                    var ship =
                        r.IsDelivery == true
                            ? (r.IsUrgent == true ? "Delivery (Urgent)" : "Delivery")
                            : "Pickup";

                    BodyCell(t, ship);
                    BodyCell(t, $"{r.CategoryLineRevenue:0.000}");
                }
            });

            return container;
        }
    }
}